title: CoTEDI
url: https://cotedi.eu
long_title: Computational Thinking Education for Diversity and Inclusion
logo_large: /images/CoTEDIlogo.svg
countries:
  ES: Spain
  CH: Switzerland
  DE: Germany
  PT: Portugal
  SE: Sweden
  NL: The Netherlands

# language code mapping is not used by the web site directly but is used by the issue-to-page action
# to assign issues to team members based on the language of the issue body
#
# the language mapping should be done by partner capabilities and not by country
languages:
  Spanish:
  - ES
  German:
  - DE
  - CH
  - AT
  Dutch: 
  - NL
  - BE
  Portuguese:
  - PT
  Swedish:
  - SE
  English:
  - GB
  - US
  - CH
  - SE
