name: Get in touch
description: Use this form to get in touch with the project team.
title: "[Short description of your request]"
projects: 
  - Community
labels: 
  - Get in touch
body:
  - type: textarea
    id: message
    attributes:
      label: Your message
      description: Why you want to get in touch with us.
      placeholder: |
        A clear and concise description of what the bug is.
        
  - type: dropdown
    id: category
    attributes:
      label: What is your request about?
      description: Your full name
      options:
        - General Inquiry
        - Media Inquiry
        - Event Inquiry
        - Technical Inquiry
  - type: dropdown
    id: language
    attributes:
      label: What is your preferred language?
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
