name: Get in touch
description: Use this form to get in touch with the project team.
title: "[Short title of your request]"
projects: 
  - cotedi-project/1
labels: 
  - Get in touch
body:
  - type: markdown
    attributes:
      value: |
        ## Get in touch
        Use this form to get in touch with the project team. We will get back to you as soon as possible.

        If you want to get in touch with us in a different language, please let us know in the language dropdown.

        If you have clicked on this template by accident, please head back to the [CoTEDI website](https://cotedi.eu/pages/contact).
  - type: textarea
    id: message
    attributes:
      label: Your message
      description: Why you want to get in touch with us?
      placeholder: |
        A clear and concise description for us. You don't have to use English. We speak many languages (see below).
        
  - type: dropdown
    id: category
    attributes:
      label: What is your request about?
      options:
        - General Inquiry
        - Media Inquiry (interviews)
        - Event Inquiry
        - Technical Inquiry
      default: 0
  - type: dropdown
    id: language
    attributes:
      label: What is your preferred language?
      description: Tell us which language you communicate best in.
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
      default: 1
