---
name: News entry
description: Use this form to add an article or blog post to the news section.
title: "[Title of the news entry]"
projects: 
  - Community
labels: 
- 📢 news
body:
  - type: markdown
    attributes:
      value: |
        **Please place a short description here.**
        A clear and concise description why you want to get in touch with us.
        Add any images here, too.
  - type: markdown 
    id: heroimage
    attributes:
      label: Banner Image
      description: The image that will be displayed on top of the news page
      placeholder:
  - type: input
    id: url
    attributes:
      label: External Link
      description: the link to the source (optional)
      placeholder:
  - type: dropdown
    id: language
    attributes:
      label: language of the article?
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
--- 