name: News entry
description: Use this form to add an article or blog post to the news section.
title: "[News] "
projects: 
  - cotedi-project/1
labels: 
  - 📢 news
body:
  - type: textarea 
    id: heroimage
    attributes:
      label: Banner Image
      description: The image that will be displayed on top of the news page. Only the first image will be used. All text is ignored. 

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Please add a few words to start your article with. This will be displayed on the news overview page and on social media. No markdown allowed.


  - type: textarea
    attributes:
      label: Announcement
      placeholder: |
        Please place the announcement here. It will be added as content of the news entry. You can drag and drop images into this field, too. These images will appear as part of the content.

  - type: input
    id: url
    attributes:
      label: External Link
      placeholder: The link to the source (optional)
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: The language of the news entry
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
      default: 1
  - type: textarea
    id: partners
    attributes:
      label: Project partners
      description: Add all additional project partners who ar involved in the event
      placeholder: |
        Leave empty if it is just you (or your team).
        Use a list for each partner involved
