--- 
name: News entry
description: Use this form to add an article or blog post to the news section.
title: "[Title of the news entry]"
projects: 
  - Community
labels: 
  - 🎥 media news
body:
  - type: textarea
    attributes:
      label: Please place a short description here.
      placeholder: |
        Please place the announcement of the media file here
        Add any images here, too.
  - type: textarea 
    id: heroimage
    attributes:
      label: Banner Image
      description: This image will be used as a placeholder before the video is actually loaded 
      placeholder:
  - type: input
    id: url
    attributes:
      label: External Link
      description: the link to the source (optional)
      placeholder:
  - type: input
    id: mediaplayer
    attributes:
      label: embed code of a mediaplayer 
      description: the link to the source (optional)
      placeholder:
  - type: input
    id: mediaurl  
    attributes:
      label: link to the source file 
      description: the link to the source media (will build a separate media player)
      placeholder:
    - type: dropdown
    id: language
    attributes:
      label: spoken language of the media?
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
---