--- 
name: Media News entry
description: Use this form to add Media file to the news section.
title: "[In the Media]"
projects: 
  - cotedi-project/1
labels: 
  - 🎥 media news
body:
  - type: textarea 
    id: heroimage
    attributes:
      label: Banner Image
      description: |
        The image that will be displayed on top of the news page. Only the first image will be used. All text is ignored.  

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Please add a few words to start your article with. This will be displayed on the news overview page and on social media. No markdown allowed.

  - type: textarea
    attributes:
      label: Announcement
      placeholder: |
        Please place the announcement of the media file here
        Add any images here, too.
  
  - type: input
    id: url
    attributes:
      label: External Link
      description: the link to the source (optional)
  - type: input
    id: mediaplayer
    attributes:
      label: Embed code of a mediaplayer 
      description: the link to the source (optional)
  - type: dropdown
    id: language
    attributes:
      label: Language of the media?
      default: 1
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
  - type: textarea
    id: partners
    attributes:
      label: Project partners
      description: Add all project partners involved in the event
      placeholder: |
        Leave empty if it is just you (or your team).
        Use a list for each partner involved
--- 
