---
name: Event
description: Use this form to add an entry to the upcoming events section.
title: "[Title of the event]"
projects: 
  - Community
labels: 
  - 📅 Event
body:
  - type: input
    id: startdate
    attributes:
      label: Start Date
      description: The date of the event
      placeholder:
  - type: input
    id: enddate
    attributes:
      label: End Date
      description: For multi day events, add the last date of the event
      placeholder:
  - type: textarea
    attributes:
      label: Please place a description of the event.
      placeholder: |
        Everything here will become the content of the news article.
        Add any images here, too.
  - type: textarea 
    id: heroimage
    attributes:
      label: Banner Image
      description: The image that will be displayed on top of the news page
      placeholder:
  - type: input
    id: url
    attributes:
      label: Main Link of the Event
      description: the link to the event
      placeholder:
  - type: input
    id: location
    attributes:
      label: Location
      description: The location of the event
      placeholder:
  - type: input
    id: country
    attributes:
      label: Country
      description: In which country the event takes place
      placeholder:
  - type: textarea
    id: partners
    attributes:
      label: Project partners
      description: Add all project partners involved in the event
      placeholder: |
        Leave empty if it is just you (or your team).
        Use a list for each partner involved
     
  - type: checkboxes
    id: is_internal
    attributes:
      label: Internal Event
      description: Check if the event is an internal event
      options:
        - label: Internal Event
          required: false
  - type: dropdown
    id: eventtype
    attributes:
      label: Event Type
      description: Choose the type of the event
      multiple: true
      options:
        - label: Conference
          value: conference
        - label: Workshop
          value: workshop
        - label: Webinar
          value: webinar
        - label: Hackathon
          value: hackathon
        - label: Meetup
          value: meetup
        - label: Training
          value: training
        - label: Other
          value: other
  - type: dropdown
    id: language
    attributes:
      label: language of the event?
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
---