--- 
name: Event Report
description: Use this form to report about an event, that will be added to the news section and in the overall reporting.
title: "[Event Report]"
projects: 
  - cotedi-project/1
labels: 
  - 📅 Event Report
body:
  - type: textarea 
    id: heroimage
    attributes:
      label: Banner Image
      description: The image that will be displayed on top of the news page

  - type: input
    id: eventlink
    attributes:
      label: Number of the Event Announcement
      description: Will reuse the information about the event.

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Please add a few words to start your article with. This will be displayed on the news overview page and on social media. No markdown allowed.

  - type: textarea
    attributes:
      label: Report
      description: |
        Everything here will become the content of the news article AND in the event reporting.
        Add any images here, too.

        Only upload images for which you have obtained the rights to use them publicly.
  
  - type: input
    id: startdate
    attributes:
      label: Start Date
      description: The date of the event (YYYY-MM-DD), e.g., 2024-01-06

  - type: input
    id: enddate
    attributes:
      label: End Date
      description: For multi day events, add the last date of the event (YYYY-MM-DD), e.g., 2024-01-06
=  - type: input
    id: url
    attributes:
      label: Main Link of the Event
      description: the link to the event
  - type: input
    id: location
    attributes:
      label: Location
      description: The location of the event
  - type: input
    id: country
    attributes:
      label: Country
      description: In which country the event took place
  - type: textarea
    id: partners
    attributes:
      label: Project partners
      description: Add all project partners involved in the event
      placeholder: |
        Leave empty if it is just you (or your team).
        Use a list for each partner involved
  - type: dropdown
    id: eventtype
    attributes:
      label: Event Type
      description: Choose the type of the event
      multiple: true
      options:
        - Conference
        - Workshop
        - Training
        - Webinar
        - Hackathon
        - Meeting
        - Other
  - type: dropdown
    id: language
    attributes:
      label: Language of the event?
      options:
        - Dutch
        - English
        - German
        - Portuguese
        - Spanish
        - Swedish
      default: 1

  - type: markdown
    attributes:
      value: |
        ## Event Details
        Please fill in the numbers of the event participants. Only fill in the fields that are relevant to the event.
  - type: textarea
    id: stats
    attributes:
      label: Statistics
      value: |
        |Country|total participants|online|teachers|parents|researchers|developers|policymakers| students|pupils|other|
        |---|---|---|---|---|---|---|---|---|---|---|
        |Total|0|0|0|0|0|0|0|0|0|0|
        |Germany|0|0|0|0|0|0|0|0|0|0|
        |The Netherlands|0|0|0|0|0|0|0|0|0|0|
        |Portugal|0|0|0|0|0|0|0|0|0|0|
        |Spain|0|0|0|0|0|0|0|0|0|0|
        |Sweden|0|0|0|0|0|0|0|0|0|0|
        |Switzerland|0|0|0|0|0|0|0|0|0|0|
        |Other EU/EWR|0|0|0|0|0|0|0|0|0|0|
        |Other non-EU/EWR|0|0|0|0|0|0|0|0|0|0|
--- 
