---
name: Technical Changes
description: Use this template for requesting new technical features.
title: "[BUG]: [FEATURE NAME]"
labels: 
  - technical
  - bug
body:
- type: markdown
  attributes:
    value: |
      **Please place a short description here.**
      A clear and concise description what needs to be changed.
- type: textarea
  id: description
  attributes:
    label: Detailed description
    description: A clear and concise description of what the bug is.
    placeholder: |
      A clear and concise description of what the bug is.
- type: dropdown 
  id: category
  attributes:
    label: technical category
    multiple: false
    options:
      - Logos
      - Typos
      - Links
      - Images
      - Layout (css)
      - JavaScript
      - Organisation
      - Automation
      - Other
---