---
name: Technical Changes
description: Use this template for requesting new technical features.
title: "[Problem]: "
labels: 
  - technical
  - bug
body:
- type: textarea
  id: present
  attributes:
    label: Present behaviour
    description:
    placeholder: |
      A clear and concise description of what is happening.
- type: textarea
  id: expected
  attributes:
    label: Expected behaviour
    description:
    placeholder: |
      A clear and concise description of what should be happening.
- type: textarea
  id: description
  attributes:
    label: Additional information
    description: A clear and concise description of what the bug is.
    placeholder: |
      Additional information about what the bug is or how to solve id
- type: dropdown 
  id: category
  attributes:
    label: Category
    description: What type of problem are you experiencing?
    multiple: false
    options:
      - Logos
      - Typos
      - Links
      - Images
      - Layout (css or html)
      - Interaction (JavaScript)
      - Organisation
      - Automation
      - Other
---