---
name: Technical Changes
description: Use this template for requesting new technical features.
title: "[BUG]: [FEATURE NAME]"
labels: 
  - technical
  - bug
body:
- type: markdown
  attributes:
    value: |
      **Please place a short description here.**
      A clear and concise description what needs to be changed.
- type: dropdown 
  id: category
  attributes:
    label: technical category
    multiple: false
    options:
      - logos
      - typos
      - layout (css)
      - JavaScript
      - Organisation
      - Timing
---