---
name: Technical Changes
description: Use this template for requesting new technical features.
title: "[BUG]: "
labels: 
  - technical
  - bug
body:
- type: textarea
  id: description
  attributes:
    label: Detailed description
    description: A clear and concise description of what the bug is.
    placeholder: |
      A clear and concise description of what the bug is.
- type: dropdown 
  id: category
  attributes:
    label: Category
    description: What type of problem are you experiencing?
    multiple: false
    options:
      - Logos
      - Typos
      - Links
      - Images
      - Layout (css or html)
      - Interaction (JavaScript)
      - Organisation
      - Automation
      - Other
---