# This workflow will run the test_wp_api.py script to fetch content from the WordPress API and save it to a Markdown file. It will then commit and push the changes to the repository.

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  get-content:

    runs-on: ubuntu-latest
    name: Get content of website

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Get content of website
      id: get-content
      run: python3 scr/test_wp_api.py
      shell: bash