# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  # Single deploy job since we're just deploying
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: check news issue
      # issue action  that load the issue author, body and all related images
        uses: phish108/issue-to-page@main
        id: news_issue
        with:
          label: '📢 News'
          target-folder: 'docs/news'
          template: '_system/form_templates/news.njk'
          formhints: '_system/forms/news.yaml'

      - name: check event announcement
      # issue action  that loads the issue author, body and all related images
        uses: phish108/issue-to-page@main
        id: event_issue
        with:
          label: 📅 Event
          target-folder: docs/events
          template: _system/form_templates/event.njk
          formhints: _system/forms/event.yaml

      - name: check media coverage
      # issue action  that loads the issue author, body and all related images
        uses: phish108/issue-to-page@main
        id: media_issue
        with:
          label: 🎥 media news
          target-folder: docs/news
          template: _system/form_templates/media_news.njk
          formhints: _system/forms/media_news.yaml

      - name: check event report 
      # issue action  that loads the issue author, body and all related images
        uses: phish108/issue-to-page@main
        id: report_issue
        with:
          label: 📅 Event Report
          target-folder: docs/reports
          template: _system/form_templates/event_report.njk
          formhints: _system/forms/event_report.yaml

      # - name: assign by language
      # # issue action that assignes the issue to a team member based on the language of the issue body
      #   uses: phish108/assign-by-language@v1
      #   with:
      #     label: Get in touch
      #     team: ./_data/partners.yaml

      - name: commit any new files
        uses: stefanzweifel/git-auto-commit-action@v5

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: setup dependencies
      #   run: npm ci
      # - name: Build site assets
      #   run: npm run all
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload entire repository
      #     path: './_site/'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
